apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: courses.hobbyfarm.io
spec:
  group: hobbyfarm.io
  versions:
  - name: v1
    storage: true
    served: true
  names:
    kind: Course
    plural: courses
  scope: Cluster
