apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dynamicbindconfigurations.hobbyfarm.io
spec:
  group: hobbyfarm.io
  versions:
    - name: v1
      storage: true
      served: true
  names:
    kind: DynamicBindConfiguration
    plural: dynamicbindconfigurations
    singular: dynamicbindconfiguration
    shortNames:
    - dbc
  scope: Cluster