apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenarios.hobbyfarm.io
spec:
  group: hobbyfarm.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Scenario
    plural: scenarios
  scope: Cluster