stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.12
      shellScript: |-
        mkdir -p /go/src/github.com/hobbyfarm
        ln -s `pwd` /go/src/github.com/hobbyfarm/gargantua
        cd /go/src/github.com/hobbyfarm/gargantua
        go build -o bin/gargantua
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gargantua:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy-api.yaml
  - applyYamlConfig:
      path: ./deploy/deploy-controllers.yaml
  - applyYamlConfig:
      path: ./deploy/deploy-shell.yaml
timeout: 60
notification: {}
