stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./cicd/docker/Dockerfile
      buildContext: .
      tag: gargantua:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deploy-api.yaml
  - applyYamlConfig:
      path: ./deploy/deploy-controllers.yaml
  - applyYamlConfig:
      path: ./deploy/deploy-shell.yaml
timeout: 60
notification: {}
