/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/v3/pkg/apis/hobbyfarm.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CourseLister helps list Courses.
// All objects returned here must be treated as read-only.
type CourseLister interface {
	// List lists all Courses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hobbyfarmiov1.Course, err error)
	// Courses returns an object that can list and get Courses.
	Courses(namespace string) CourseNamespaceLister
	CourseListerExpansion
}

// courseLister implements the CourseLister interface.
type courseLister struct {
	listers.ResourceIndexer[*hobbyfarmiov1.Course]
}

// NewCourseLister returns a new CourseLister.
func NewCourseLister(indexer cache.Indexer) CourseLister {
	return &courseLister{listers.New[*hobbyfarmiov1.Course](indexer, hobbyfarmiov1.Resource("course"))}
}

// Courses returns an object that can list and get Courses.
func (s *courseLister) Courses(namespace string) CourseNamespaceLister {
	return courseNamespaceLister{listers.NewNamespaced[*hobbyfarmiov1.Course](s.ResourceIndexer, namespace)}
}

// CourseNamespaceLister helps list and get Courses.
// All objects returned here must be treated as read-only.
type CourseNamespaceLister interface {
	// List lists all Courses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hobbyfarmiov1.Course, err error)
	// Get retrieves the Course from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hobbyfarmiov1.Course, error)
	CourseNamespaceListerExpansion
}

// courseNamespaceLister implements the CourseNamespaceLister
// interface.
type courseNamespaceLister struct {
	listers.ResourceIndexer[*hobbyfarmiov1.Course]
}
