/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v12 "github.com/hobbyfarm/gargantua/v3/pkg/apis/hobbyfarm.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VirtualMachineTemplateLister helps list VirtualMachineTemplates.
// All objects returned here must be treated as read-only.
type VirtualMachineTemplateLister interface {
	// List lists all VirtualMachineTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v12.VirtualMachineTemplate, err error)
	// VirtualMachineTemplates returns an object that can list and get VirtualMachineTemplates.
	VirtualMachineTemplates(namespace string) VirtualMachineTemplateNamespaceLister
	VirtualMachineTemplateListerExpansion
}

// virtualMachineTemplateLister implements the VirtualMachineTemplateLister interface.
type virtualMachineTemplateLister struct {
	indexer cache.Indexer
}

// NewVirtualMachineTemplateLister returns a new VirtualMachineTemplateLister.
func NewVirtualMachineTemplateLister(indexer cache.Indexer) VirtualMachineTemplateLister {
	return &virtualMachineTemplateLister{indexer: indexer}
}

// List lists all VirtualMachineTemplates in the indexer.
func (s *virtualMachineTemplateLister) List(selector labels.Selector) (ret []*v12.VirtualMachineTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v12.VirtualMachineTemplate))
	})
	return ret, err
}

// VirtualMachineTemplates returns an object that can list and get VirtualMachineTemplates.
func (s *virtualMachineTemplateLister) VirtualMachineTemplates(namespace string) VirtualMachineTemplateNamespaceLister {
	return virtualMachineTemplateNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VirtualMachineTemplateNamespaceLister helps list and get VirtualMachineTemplates.
// All objects returned here must be treated as read-only.
type VirtualMachineTemplateNamespaceLister interface {
	// List lists all VirtualMachineTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v12.VirtualMachineTemplate, err error)
	// Get retrieves the VirtualMachineTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v12.VirtualMachineTemplate, error)
	VirtualMachineTemplateNamespaceListerExpansion
}

// virtualMachineTemplateNamespaceLister implements the VirtualMachineTemplateNamespaceLister
// interface.
type virtualMachineTemplateNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VirtualMachineTemplates in the indexer for a given namespace.
func (s virtualMachineTemplateNamespaceLister) List(selector labels.Selector) (ret []*v12.VirtualMachineTemplate, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v12.VirtualMachineTemplate))
	})
	return ret, err
}

// Get retrieves the VirtualMachineTemplate from the indexer for a given namespace and name.
func (s virtualMachineTemplateNamespaceLister) Get(name string) (*v12.VirtualMachineTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v12.Resource("virtualmachinetemplate"), name)
	}
	return obj.(*v12.VirtualMachineTemplate), nil
}
