/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/v3/pkg/apis/hobbyfarm.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualMachineSetLister helps list VirtualMachineSets.
// All objects returned here must be treated as read-only.
type VirtualMachineSetLister interface {
	// List lists all VirtualMachineSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hobbyfarmiov1.VirtualMachineSet, err error)
	// VirtualMachineSets returns an object that can list and get VirtualMachineSets.
	VirtualMachineSets(namespace string) VirtualMachineSetNamespaceLister
	VirtualMachineSetListerExpansion
}

// virtualMachineSetLister implements the VirtualMachineSetLister interface.
type virtualMachineSetLister struct {
	listers.ResourceIndexer[*hobbyfarmiov1.VirtualMachineSet]
}

// NewVirtualMachineSetLister returns a new VirtualMachineSetLister.
func NewVirtualMachineSetLister(indexer cache.Indexer) VirtualMachineSetLister {
	return &virtualMachineSetLister{listers.New[*hobbyfarmiov1.VirtualMachineSet](indexer, hobbyfarmiov1.Resource("virtualmachineset"))}
}

// VirtualMachineSets returns an object that can list and get VirtualMachineSets.
func (s *virtualMachineSetLister) VirtualMachineSets(namespace string) VirtualMachineSetNamespaceLister {
	return virtualMachineSetNamespaceLister{listers.NewNamespaced[*hobbyfarmiov1.VirtualMachineSet](s.ResourceIndexer, namespace)}
}

// VirtualMachineSetNamespaceLister helps list and get VirtualMachineSets.
// All objects returned here must be treated as read-only.
type VirtualMachineSetNamespaceLister interface {
	// List lists all VirtualMachineSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*hobbyfarmiov1.VirtualMachineSet, err error)
	// Get retrieves the VirtualMachineSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*hobbyfarmiov1.VirtualMachineSet, error)
	VirtualMachineSetNamespaceListerExpansion
}

// virtualMachineSetNamespaceLister implements the VirtualMachineSetNamespaceLister
// interface.
type virtualMachineSetNamespaceLister struct {
	listers.ResourceIndexer[*hobbyfarmiov1.VirtualMachineSet]
}
