/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	terraformcontrollercattleiov1 "github.com/hobbyfarm/gargantua/v3/pkg/apis/terraformcontroller.cattle.io/v1"
	scheme "github.com/hobbyfarm/gargantua/v3/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModulesGetter has a method to return a ModuleInterface.
// A group's client should implement this interface.
type ModulesGetter interface {
	Modules(namespace string) ModuleInterface
}

// ModuleInterface has methods to work with Module resources.
type ModuleInterface interface {
	Create(ctx context.Context, module *terraformcontrollercattleiov1.Module, opts metav1.CreateOptions) (*terraformcontrollercattleiov1.Module, error)
	Update(ctx context.Context, module *terraformcontrollercattleiov1.Module, opts metav1.UpdateOptions) (*terraformcontrollercattleiov1.Module, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, module *terraformcontrollercattleiov1.Module, opts metav1.UpdateOptions) (*terraformcontrollercattleiov1.Module, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*terraformcontrollercattleiov1.Module, error)
	List(ctx context.Context, opts metav1.ListOptions) (*terraformcontrollercattleiov1.ModuleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *terraformcontrollercattleiov1.Module, err error)
	ModuleExpansion
}

// modules implements ModuleInterface
type modules struct {
	*gentype.ClientWithList[*terraformcontrollercattleiov1.Module, *terraformcontrollercattleiov1.ModuleList]
}

// newModules returns a Modules
func newModules(c *TerraformcontrollerV1Client, namespace string) *modules {
	return &modules{
		gentype.NewClientWithList[*terraformcontrollercattleiov1.Module, *terraformcontrollercattleiov1.ModuleList](
			"modules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *terraformcontrollercattleiov1.Module { return &terraformcontrollercattleiov1.Module{} },
			func() *terraformcontrollercattleiov1.ModuleList { return &terraformcontrollercattleiov1.ModuleList{} },
		),
	}
}
