/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// AccessCodeListerExpansion allows custom methods to be added to
// AccessCodeLister.
type AccessCodeListerExpansion interface{}

// DynamicBindConfigurationListerExpansion allows custom methods to be added to
// DynamicBindConfigurationLister.
type DynamicBindConfigurationListerExpansion interface{}

// DynamicBindRequestListerExpansion allows custom methods to be added to
// DynamicBindRequestLister.
type DynamicBindRequestListerExpansion interface{}

// EnvironmentListerExpansion allows custom methods to be added to
// EnvironmentLister.
type EnvironmentListerExpansion interface{}

// ScenarioListerExpansion allows custom methods to be added to
// ScenarioLister.
type ScenarioListerExpansion interface{}

// ScenarioSessionListerExpansion allows custom methods to be added to
// ScenarioSessionLister.
type ScenarioSessionListerExpansion interface{}

// ScheduledEventListerExpansion allows custom methods to be added to
// ScheduledEventLister.
type ScheduledEventListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineClaimListerExpansion allows custom methods to be added to
// VirtualMachineClaimLister.
type VirtualMachineClaimListerExpansion interface{}

// VirtualMachineSetListerExpansion allows custom methods to be added to
// VirtualMachineSetLister.
type VirtualMachineSetListerExpansion interface{}

// VirtualMachineTemplateListerExpansion allows custom methods to be added to
// VirtualMachineTemplateLister.
type VirtualMachineTemplateListerExpansion interface{}
