// Code generated by lister-gen. DO NOT EDIT.

package v1

// AccessCodeListerExpansion allows custom methods to be added to
// AccessCodeLister.
type AccessCodeListerExpansion interface{}

// CourseListerExpansion allows custom methods to be added to
// CourseLister.
type CourseListerExpansion interface{}

// CourseSessionListerExpansion allows custom methods to be added to
// CourseSessionLister.
type CourseSessionListerExpansion interface{}

// DynamicBindConfigurationListerExpansion allows custom methods to be added to
// DynamicBindConfigurationLister.
type DynamicBindConfigurationListerExpansion interface{}

// DynamicBindRequestListerExpansion allows custom methods to be added to
// DynamicBindRequestLister.
type DynamicBindRequestListerExpansion interface{}

// EnvironmentListerExpansion allows custom methods to be added to
// EnvironmentLister.
type EnvironmentListerExpansion interface{}

// ScenarioListerExpansion allows custom methods to be added to
// ScenarioLister.
type ScenarioListerExpansion interface{}

// ScheduledEventListerExpansion allows custom methods to be added to
// ScheduledEventLister.
type ScheduledEventListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineClaimListerExpansion allows custom methods to be added to
// VirtualMachineClaimLister.
type VirtualMachineClaimListerExpansion interface{}

// VirtualMachineSetListerExpansion allows custom methods to be added to
// VirtualMachineSetLister.
type VirtualMachineSetListerExpansion interface{}

// VirtualMachineTemplateListerExpansion allows custom methods to be added to
// VirtualMachineTemplateLister.
type VirtualMachineTemplateListerExpansion interface{}
