// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/hobbyfarm/gargantua/pkg/apis/hobbyfarm.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ScenarioSessionLister helps list ScenarioSessions.
type ScenarioSessionLister interface {
	// List lists all ScenarioSessions in the indexer.
	List(selector labels.Selector) (ret []*v1.ScenarioSession, err error)
	// Get retrieves the ScenarioSession from the index for a given name.
	Get(name string) (*v1.ScenarioSession, error)
	ScenarioSessionListerExpansion
}

// scenarioSessionLister implements the ScenarioSessionLister interface.
type scenarioSessionLister struct {
	indexer cache.Indexer
}

// NewScenarioSessionLister returns a new ScenarioSessionLister.
func NewScenarioSessionLister(indexer cache.Indexer) ScenarioSessionLister {
	return &scenarioSessionLister{indexer: indexer}
}

// List lists all ScenarioSessions in the indexer.
func (s *scenarioSessionLister) List(selector labels.Selector) (ret []*v1.ScenarioSession, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ScenarioSession))
	})
	return ret, err
}

// Get retrieves the ScenarioSession from the index for a given name.
func (s *scenarioSessionLister) Get(name string) (*v1.ScenarioSession, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("scenariosession"), name)
	}
	return obj.(*v1.ScenarioSession), nil
}
