// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/hobbyfarm/gargantua/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Executions returns a ExecutionInformer.
	Executions() ExecutionInformer
	// Modules returns a ModuleInformer.
	Modules() ModuleInformer
	// States returns a StateInformer.
	States() StateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Executions returns a ExecutionInformer.
func (v *version) Executions() ExecutionInformer {
	return &executionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Modules returns a ModuleInformer.
func (v *version) Modules() ModuleInformer {
	return &moduleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// States returns a StateInformer.
func (v *version) States() StateInformer {
	return &stateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
