/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/pkg/apis/hobbyfarm.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineClaims implements VirtualMachineClaimInterface
type FakeVirtualMachineClaims struct {
	Fake *FakeHobbyfarmV1
}

var virtualmachineclaimsResource = schema.GroupVersionResource{Group: "hobbyfarm.io", Version: "v1", Resource: "virtualmachineclaims"}

var virtualmachineclaimsKind = schema.GroupVersionKind{Group: "hobbyfarm.io", Version: "v1", Kind: "VirtualMachineClaim"}

// Get takes name of the virtualMachineClaim, and returns the corresponding virtualMachineClaim object, and an error if there is any.
func (c *FakeVirtualMachineClaims) Get(name string, options v1.GetOptions) (result *hobbyfarmiov1.VirtualMachineClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(virtualmachineclaimsResource, name), &hobbyfarmiov1.VirtualMachineClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineClaim), err
}

// List takes label and field selectors, and returns the list of VirtualMachineClaims that match those selectors.
func (c *FakeVirtualMachineClaims) List(opts v1.ListOptions) (result *hobbyfarmiov1.VirtualMachineClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(virtualmachineclaimsResource, virtualmachineclaimsKind, opts), &hobbyfarmiov1.VirtualMachineClaimList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hobbyfarmiov1.VirtualMachineClaimList{ListMeta: obj.(*hobbyfarmiov1.VirtualMachineClaimList).ListMeta}
	for _, item := range obj.(*hobbyfarmiov1.VirtualMachineClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineClaims.
func (c *FakeVirtualMachineClaims) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(virtualmachineclaimsResource, opts))
}

// Create takes the representation of a virtualMachineClaim and creates it.  Returns the server's representation of the virtualMachineClaim, and an error, if there is any.
func (c *FakeVirtualMachineClaims) Create(virtualMachineClaim *hobbyfarmiov1.VirtualMachineClaim) (result *hobbyfarmiov1.VirtualMachineClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(virtualmachineclaimsResource, virtualMachineClaim), &hobbyfarmiov1.VirtualMachineClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineClaim), err
}

// Update takes the representation of a virtualMachineClaim and updates it. Returns the server's representation of the virtualMachineClaim, and an error, if there is any.
func (c *FakeVirtualMachineClaims) Update(virtualMachineClaim *hobbyfarmiov1.VirtualMachineClaim) (result *hobbyfarmiov1.VirtualMachineClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(virtualmachineclaimsResource, virtualMachineClaim), &hobbyfarmiov1.VirtualMachineClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineClaims) UpdateStatus(virtualMachineClaim *hobbyfarmiov1.VirtualMachineClaim) (*hobbyfarmiov1.VirtualMachineClaim, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(virtualmachineclaimsResource, "status", virtualMachineClaim), &hobbyfarmiov1.VirtualMachineClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineClaim), err
}

// Delete takes name of the virtualMachineClaim and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineClaims) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(virtualmachineclaimsResource, name), &hobbyfarmiov1.VirtualMachineClaim{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineClaims) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(virtualmachineclaimsResource, listOptions)

	_, err := c.Fake.Invokes(action, &hobbyfarmiov1.VirtualMachineClaimList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineClaim.
func (c *FakeVirtualMachineClaims) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hobbyfarmiov1.VirtualMachineClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(virtualmachineclaimsResource, name, pt, data, subresources...), &hobbyfarmiov1.VirtualMachineClaim{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineClaim), err
}
