/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/pkg/apis/hobbyfarm.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineTemplates implements VirtualMachineTemplateInterface
type FakeVirtualMachineTemplates struct {
	Fake *FakeHobbyfarmV1
}

var virtualmachinetemplatesResource = schema.GroupVersionResource{Group: "hobbyfarm.io", Version: "v1", Resource: "virtualmachinetemplates"}

var virtualmachinetemplatesKind = schema.GroupVersionKind{Group: "hobbyfarm.io", Version: "v1", Kind: "VirtualMachineTemplate"}

// Get takes name of the virtualMachineTemplate, and returns the corresponding virtualMachineTemplate object, and an error if there is any.
func (c *FakeVirtualMachineTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *hobbyfarmiov1.VirtualMachineTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(virtualmachinetemplatesResource, name), &hobbyfarmiov1.VirtualMachineTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineTemplate), err
}

// List takes label and field selectors, and returns the list of VirtualMachineTemplates that match those selectors.
func (c *FakeVirtualMachineTemplates) List(ctx context.Context, opts v1.ListOptions) (result *hobbyfarmiov1.VirtualMachineTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(virtualmachinetemplatesResource, virtualmachinetemplatesKind, opts), &hobbyfarmiov1.VirtualMachineTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hobbyfarmiov1.VirtualMachineTemplateList{ListMeta: obj.(*hobbyfarmiov1.VirtualMachineTemplateList).ListMeta}
	for _, item := range obj.(*hobbyfarmiov1.VirtualMachineTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineTemplates.
func (c *FakeVirtualMachineTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(virtualmachinetemplatesResource, opts))
}

// Create takes the representation of a virtualMachineTemplate and creates it.  Returns the server's representation of the virtualMachineTemplate, and an error, if there is any.
func (c *FakeVirtualMachineTemplates) Create(ctx context.Context, virtualMachineTemplate *hobbyfarmiov1.VirtualMachineTemplate, opts v1.CreateOptions) (result *hobbyfarmiov1.VirtualMachineTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(virtualmachinetemplatesResource, virtualMachineTemplate), &hobbyfarmiov1.VirtualMachineTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineTemplate), err
}

// Update takes the representation of a virtualMachineTemplate and updates it. Returns the server's representation of the virtualMachineTemplate, and an error, if there is any.
func (c *FakeVirtualMachineTemplates) Update(ctx context.Context, virtualMachineTemplate *hobbyfarmiov1.VirtualMachineTemplate, opts v1.UpdateOptions) (result *hobbyfarmiov1.VirtualMachineTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(virtualmachinetemplatesResource, virtualMachineTemplate), &hobbyfarmiov1.VirtualMachineTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineTemplate), err
}

// Delete takes name of the virtualMachineTemplate and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(virtualmachinetemplatesResource, name), &hobbyfarmiov1.VirtualMachineTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(virtualmachinetemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &hobbyfarmiov1.VirtualMachineTemplateList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineTemplate.
func (c *FakeVirtualMachineTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hobbyfarmiov1.VirtualMachineTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(virtualmachinetemplatesResource, name, pt, data, subresources...), &hobbyfarmiov1.VirtualMachineTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineTemplate), err
}
