/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	hobbyfarmiov1 "github.com/hobbyfarm/gargantua/pkg/apis/hobbyfarm.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualMachineTypes implements VirtualMachineTypeInterface
type FakeVirtualMachineTypes struct {
	Fake *FakeHobbyfarmV1
	ns   string
}

var virtualmachinetypesResource = schema.GroupVersionResource{Group: "hobbyfarm.io", Version: "v1", Resource: "virtualmachinetypes"}

var virtualmachinetypesKind = schema.GroupVersionKind{Group: "hobbyfarm.io", Version: "v1", Kind: "VirtualMachineType"}

// Get takes name of the virtualMachineType, and returns the corresponding virtualMachineType object, and an error if there is any.
func (c *FakeVirtualMachineTypes) Get(name string, options v1.GetOptions) (result *hobbyfarmiov1.VirtualMachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualmachinetypesResource, c.ns, name), &hobbyfarmiov1.VirtualMachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineType), err
}

// List takes label and field selectors, and returns the list of VirtualMachineTypes that match those selectors.
func (c *FakeVirtualMachineTypes) List(opts v1.ListOptions) (result *hobbyfarmiov1.VirtualMachineTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualmachinetypesResource, virtualmachinetypesKind, c.ns, opts), &hobbyfarmiov1.VirtualMachineTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hobbyfarmiov1.VirtualMachineTypeList{ListMeta: obj.(*hobbyfarmiov1.VirtualMachineTypeList).ListMeta}
	for _, item := range obj.(*hobbyfarmiov1.VirtualMachineTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineTypes.
func (c *FakeVirtualMachineTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualmachinetypesResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineType and creates it.  Returns the server's representation of the virtualMachineType, and an error, if there is any.
func (c *FakeVirtualMachineTypes) Create(virtualMachineType *hobbyfarmiov1.VirtualMachineType) (result *hobbyfarmiov1.VirtualMachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualmachinetypesResource, c.ns, virtualMachineType), &hobbyfarmiov1.VirtualMachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineType), err
}

// Update takes the representation of a virtualMachineType and updates it. Returns the server's representation of the virtualMachineType, and an error, if there is any.
func (c *FakeVirtualMachineTypes) Update(virtualMachineType *hobbyfarmiov1.VirtualMachineType) (result *hobbyfarmiov1.VirtualMachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualmachinetypesResource, c.ns, virtualMachineType), &hobbyfarmiov1.VirtualMachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineType), err
}

// Delete takes name of the virtualMachineType and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineTypes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualmachinetypesResource, c.ns, name), &hobbyfarmiov1.VirtualMachineType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualmachinetypesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &hobbyfarmiov1.VirtualMachineTypeList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineType.
func (c *FakeVirtualMachineTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *hobbyfarmiov1.VirtualMachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachinetypesResource, c.ns, name, pt, data, subresources...), &hobbyfarmiov1.VirtualMachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hobbyfarmiov1.VirtualMachineType), err
}
