/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/hobbyfarm/gargantua/v3/pkg/apis/hobbyfarm.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDynamicBindConfigurations implements DynamicBindConfigurationInterface
type FakeDynamicBindConfigurations struct {
	Fake *FakeHobbyfarmV1
	ns   string
}

var dynamicbindconfigurationsResource = v1.SchemeGroupVersion.WithResource("dynamicbindconfigurations")

var dynamicbindconfigurationsKind = v1.SchemeGroupVersion.WithKind("DynamicBindConfiguration")

// Get takes name of the dynamicBindConfiguration, and returns the corresponding dynamicBindConfiguration object, and an error if there is any.
func (c *FakeDynamicBindConfigurations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DynamicBindConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dynamicbindconfigurationsResource, c.ns, name), &v1.DynamicBindConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DynamicBindConfiguration), err
}

// List takes label and field selectors, and returns the list of DynamicBindConfigurations that match those selectors.
func (c *FakeDynamicBindConfigurations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DynamicBindConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dynamicbindconfigurationsResource, dynamicbindconfigurationsKind, c.ns, opts), &v1.DynamicBindConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DynamicBindConfigurationList{ListMeta: obj.(*v1.DynamicBindConfigurationList).ListMeta}
	for _, item := range obj.(*v1.DynamicBindConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dynamicBindConfigurations.
func (c *FakeDynamicBindConfigurations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dynamicbindconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a dynamicBindConfiguration and creates it.  Returns the server's representation of the dynamicBindConfiguration, and an error, if there is any.
func (c *FakeDynamicBindConfigurations) Create(ctx context.Context, dynamicBindConfiguration *v1.DynamicBindConfiguration, opts metav1.CreateOptions) (result *v1.DynamicBindConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dynamicbindconfigurationsResource, c.ns, dynamicBindConfiguration), &v1.DynamicBindConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DynamicBindConfiguration), err
}

// Update takes the representation of a dynamicBindConfiguration and updates it. Returns the server's representation of the dynamicBindConfiguration, and an error, if there is any.
func (c *FakeDynamicBindConfigurations) Update(ctx context.Context, dynamicBindConfiguration *v1.DynamicBindConfiguration, opts metav1.UpdateOptions) (result *v1.DynamicBindConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dynamicbindconfigurationsResource, c.ns, dynamicBindConfiguration), &v1.DynamicBindConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DynamicBindConfiguration), err
}

// Delete takes name of the dynamicBindConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeDynamicBindConfigurations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dynamicbindconfigurationsResource, c.ns, name, opts), &v1.DynamicBindConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDynamicBindConfigurations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dynamicbindconfigurationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DynamicBindConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched dynamicBindConfiguration.
func (c *FakeDynamicBindConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DynamicBindConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dynamicbindconfigurationsResource, c.ns, name, pt, data, subresources...), &v1.DynamicBindConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DynamicBindConfiguration), err
}
